kind: pipeline
type: docker
name: Ubuntu


clone:
  disable: true


steps:
  - name: 代码
    image: dronestock/git

  - name: 发布
    image: dronestock/docker
    privileged: true
    volumes:
      - name: docker
        path: /var/lib/docker
    settings:
      repository: storezhang/ubuntu
      username: storezhang
      password:
        from_secret: token_docker
